import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button, Htag, P, Rating, Tag } from "../components";
import { useState } from "react";
import { withLayout } from "../layout/Layout";

const Home: NextPage = () => {
  const [rating, setRating] = useState(3);
  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Htag tag={"h1"}>Hello</Htag>
      <Button appearance={"primary"} arrow={"right"}>
        Click
      </Button>
      <Button appearance={"ghost"} arrow={"down"}>
        Click
      </Button>
      <P size={"s"}>Lorem ipsum dolor</P>
      <Tag size={"s"} color={"red"}>
        Tag
      </Tag>
      <Tag size={"m"} color={"green"}>
        Tag
      </Tag>
      <Rating rating={rating} isEditable={true} setRating={setRating} />
    </>
  );
};

export default withLayout(Home);
