import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button, Htag, P, Tag } from "../components";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Htag tag={"h1"}>Hello</Htag>
        <Button appearance={"primary"} arrow={"right"}>
          Click
        </Button>
        <Button appearance={"ghost"} arrow={"down"}>
          Click
        </Button>
        <P size={"s"}>Lorem ipsum dolor</P>
        <Tag size={"s"} color={"red"}>
          Tag
        </Tag>
        <Tag size={"m"} color={"green"}>
          Tag
        </Tag>
      </main>
    </div>
  );
};

export default Home;
